### ISSUE TITLE
baseUrl changed?

### ISSUE THREAD

**Issue by nathanabrewer** [kisi-inc/client-js#10]
It appears that https://my.getKisi.com/api as baseUrl does not work.
Should this be https://www.kisi.de, or is this temporary? 
if kisis api endpoint change is temporary, then maybe still allowing an override on the config object would be nice.

Any documentation? Would love to take this library and put it in a simple node-red module

btw, the errors were not handled correctly by KyleAMathews/superagent-bluebird-promise
spudly's fork of the repo worked for me in showing that my issues were indeed 405 errors from the original baseUrl. (I know there was a thread discussing that error handling anyway)

**Comment by frakti** [comment]
Regarding overriding endpoint, currently you can do it by:
```
var KisiClient = require('kisi-client');
var client = new KisiClient();
client.context.baseUrl = 'https://www.kisi.de';
```

**Comment by ce07c3** [comment]
Please use api.getkisi.com for the endpoint.
