### ISSUE TITLE
Error: Cannot find module 'lodash.clonedeep'

### ISSUE THREAD

**Issue by KevCron** [kisi-inc/client-js#15]
<img width="784" alt="screen shot 2016-04-15 at 7 20 39 pm" src="https://cloud.githubusercontent.com/assets/9090280/14577229/28fccab8-033f-11e6-87ab-f62394a9a5f9.png">

`demo.js` contains only the line `var client = require('kisi-client')`.

Run `npm install --save lodash.clonedeep' to resolve. Next error is:

<img width="786" alt="screen shot 2016-04-15 at 7 22 03 pm" src="https://cloud.githubusercontent.com/assets/9090280/14577244/5e749b4e-033f-11e6-81f8-20e1ec8dcfb6.png">

Run `npm install --save lodash.omit` to resolve.

**Comment by ce07c3** [comment]
See #18 :)
