### ISSUE TITLE
'kisi-client-js' now called 'kisi-client'

### ISSUE THREAD

**Issue by KevCron** [kisi-inc/client-js#16]
`npm install kisi-client` works, `npm install kisi-client-js` returns a 404. I believe the docs have simply not been updated. Please correct me if I am wrong. 

<img width="937" alt="screen shot 2016-04-15 at 7 25 54 pm" src="https://cloud.githubusercontent.com/assets/9090280/14577280/e9b34c8c-033f-11e6-8f6b-28837c72bbab.png">

**Comment by ce07c3** [comment]
True! Sorry for the late reply, we're just about to launch an updated version.

**Comment by ce07c3** [comment]
Updated.
