### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by ildella** [kisi-inc/client-js#27]
Hi. Everytime I run a simple code that executes login and get "places", on the firsts run I get the following error, and the second one return the actual answer. Then the third return the error again, the 4th the actual answer and so on. This happens 100% of the time running the sample code in the README.  

This is the most complete error with Node7. Node 6 only returns the second line. Node 5 and 4 does not return any error but still, odd calls fails, even calls works with every Node version, in the same way. 

```
(node:31394) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: An error occurred interacting with the Kisi API.
(node:31394) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ce07c3** [comment]
@ildella please provide code that breaks, i'll reproduce

**Comment by ildella** [comment]
const Kisi = require('kisi-client')
const kisiClient = new Kisi.default()

kisiClient
    .signIn("abc@xyz.com", "********")
    .then(() => {
        kisiClient
            .get("places")
            .then(places => console.log(places.data));
    })

**Comment by ildella** [comment]
Additional Info. If I add

```
     kisiClient		
      .post("locks/3434/unlock", {})
      .then(result => console.log(result)) // the result
      .catch(error => console.log(error)) // any error
```

then I get this message on the odd calls: 

`{ [Error: An error occurred interacting with the Kisi API.] status: 401, code: '000000', reason: 'Login not found!' }
`

**Comment by vramana** [comment]
Promises swallow error if you don't handle them explicitly. Hence, Node.js introduced throws this warning recently. The solution is to add  catch handler at the end of your promise chain.

Your second error probably is authentication failure.
